// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool.API.Data;

namespace SmartSchool.API.Migrations
{
    [DbContext(typeof(SmartContext))]
    [Migration("20201206214622_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SmartSchool.API.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("54467587-568e-4219-ab99-c2a1fae1cff4"),
                            Idade = 36,
                            Nome = "Lauro"
                        },
                        new
                        {
                            Id = new Guid("89565508-0a7e-4a77-bfaa-ea7b7882087c"),
                            Idade = 25,
                            Nome = "Roberto"
                        },
                        new
                        {
                            Id = new Guid("d463643c-6423-49d1-9c14-cda59b05632f"),
                            Idade = 32,
                            Nome = "Ronaldo"
                        },
                        new
                        {
                            Id = new Guid("34072e44-85cd-41a1-912a-fdd3d8842334"),
                            Idade = 42,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            Id = new Guid("de8ad240-fad6-44bd-b6a2-2c6994714c65"),
                            Idade = 46,
                            Nome = "Alexandre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
